### ISSUE TITLE
这边生成的token怎么这么短？

### ISSUE THREAD

**Issue by php2go** [goflyfox/gtoken#10]
例如：
`lpe0YG9uqSN+sc8zL1tF+0frgzo2GtYM5gG2p2X+O+5/Klm1YV1Jn6KJlwOBOAQcSXglG497wth6VUP1H1gWif3hqVtYkZOZLmE+l+sDPYGTsJsT403OJQjTVmASqpC3`

**Comment by zcool321** [comment]
我感觉挺长的啊

**Comment by php2go** [comment]
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwOlwvXC9saWdodGVyLm1va2FnbS5jb21cL2FwaVwvYXV0aFwvdG9rZW4iLCJpYXQiOjE2MDAwNjYyNTEsImV4cCI6MTYwMjY1ODI1MSwibmJmIjoxNjAwMDY2MjUxLCJqdGkiOiJjUk4wMEZad3E5NU1CWkc3Iiwic3ViIjoxLCJwcnYiOiI4YzJmZjY2ZjRjYjJlMTM4Zjc2ZjJhMzAxMDcxYjZjMDVjMmFhZjQ0IiwicHJvIjoibWthIiwidGVsIjoiMTEwIiwid3JkIjoiVXNpbmcgYWNjZXNzLXRva2VuIG1hbGljaW91c2x5IHdpbGwgYmUgaW4gamFpbC4ifQ.zBa6IApbIwmPV56SOa1EIo0VslO-RJjzx8nQywwTqBMbu5KA1V_ZFqqOrPzzy7iuBQ0CbBDAiz4lvy-_Ip0i_A  这个使用的HS512加密的这个长度和上面的相比而言长的很多
