### ISSUE TITLE
redis连接 aws集群需要tls配置，不然连不上

### ISSUE THREAD

**Issue by zhangyiyou5** [goflyfox/gtoken#15]
clusterOpts *redis.ClusterOptions

type ClusterOptions struct {
       ...
       TLSConfig *tls.Config
}

//只要集群有密码，tls就需要配置，tls要设置为空，希望修复一下
![image](https://user-images.githubusercontent.com/20124305/104712040-13299780-575d-11eb-9202-27bdb33b44d8.png)

**Comment by zcool321** [comment]
这个不是gtoken问题吧~可以提交到goframe框架
