### ISSUE TITLE
decrypt error ：cipherText is not a multiple of the block size

### ISSUE THREAD

**Issue by Hareis** [goflyfox/gtoken#21]
上才艺

![image](https://user-images.githubusercontent.com/11290701/130530819-27f0605f-bfc2-495b-b424-78a2752aafa8.png)

代码配置ru'xia如下
![image](https://user-images.githubusercontent.com/11290701/130530873-a4cc18a2-489c-4eb3-b974-2e8d4fba0444.png)

变量配置如下
![image](https://user-images.githubusercontent.com/11290701/130531036-2408c285-31f9-4dc7-a334-db00d7e1b9ac.png)

描述 
使用的最新版本安装的 ``github.com/goflyfox/gtoken v1.4.2``
期初以为是我加密秘钥的问题，后来换成gtoken 默认也是提示这个错误

附上请求数据
```
{
  "isSuccess": true,
  "data": {
    "token": "Q1BFcDFuWXU3K2xCZEdMUGYzam5xYzdLbGJBY2VlU3c4UEo5WGxwVnNBSnZSY0JWZTYxTnBYc0tmcUU2cDh6SFBEN2tLb2F1MVh3NFQ0SzNZOFk3VXBrdGVjNEdwa3JFQnJSaFdrcDAyNnM9",
    "userKey": "dc4778f3a9f145f6c90e123a11a46bf6",
    "uuid": "1bdad1ae172ee83f8eb267899522b41d"
  },
  "errMsg": ""
}
```

**Comment by zcool321** [comment]
经调试，你这个异常核心问题是你重写了LoginAfterFunc方法导致取的token不对，参考如下写法

```
LoginAfterFunc: func(r *ghttp.Request, respData gtoken.Resp) {
			r.Response.WriteJson(g.Map{
				"token": respData.GetString("token"),
			})
		},
```

**Comment by zcool321** [comment]
调试发现这个是golang sdk转json的一个特性，会把[]byte格式进行一次base64编码
所以你那种重写LoginAfterFunc方法返回的token是多了一次base64编码的结果，无法解析
