### ISSUE TITLE
是否支持从cookie中获取token？

### ISSUE THREAD

**Issue by legeng** [goflyfox/gtoken#22]
目前来看getRequestToken 方法，只能从header头和body或者url中获取，我有个多站点，二级域名和顶级域名共享cookie , 登录成功后把token设置到cookie中了，但是httponly了，前端js不能拿到cookie的token ，能否直接在getRequestToken 中增加一个从cookie中获取token

**Comment by zcool321** [comment]
cookie方面从设计之初没有加入考虑，后续可以考虑进行补充，欢迎提交PR
