### ISSUE TITLE
分组拦截, 登录接口不拦截中对退出登录接口没判断非空才拦截

### ISSUE THREAD

**Issue by wyaow** [goflyfox/gtoken#23]
测试用例报错
=== RUN   TestGroupAuthPath
    gtoken_test.go:41: Group auth path test 
    gtoken_test.go:67: error: /system/test auth path error
--- FAIL: TestGroupAuthPath (0.00s)
FAIL

**Comment by wyaow** [comment]
原因是：没有对退出登录接口判断是否配置了。没配置就会有点小问题。
	if m.MiddlewareType == MiddlewareTypeGroup {
		if gstr.HasSuffix(urlPath, m.LoginPath) ||
		     gstr.HasSuffix(urlPath, m.LogoutPath) {
			return false
		}
	}

应该改为
// 分组拦截，登录接口不拦截, 配置了退出登录接口不拦截
	if m.MiddlewareType == MiddlewareTypeGroup {
		if gstr.HasSuffix(urlPath, m.LoginPath) ||
			(m.LogoutPath != "" && gstr.HasSuffix(urlPath, m.LogoutPath)) {
			return false
		}
	}

**Comment by zcool321** [comment]
代码初始化有对m.LogoutPath == ""进行校验，难道你的m.LogoutPath为空？

**Comment by zcool321** [comment]
已添加
