### ISSUE TITLE
关于LoginPath的路由请求方法修改问题

### ISSUE THREAD

**Issue by mutiple** [goflyfox/gtoken#28]
你好，我想问下LoginPath的路径能不能指定请求方法？
我查了你的源代码用的BindHandler生成的路由，没办法指定请求的方法。因为不想开那么多的口，怕产生安全问题。

**Comment by mutiple** [comment]
我看生成LoginPath路由用的BindHandler方法，这个方法我看官方文档可以按照```[HTTPMethod:]路由规则[@域名] ```这个规则写。
为什么我在LoginPath里按照这个规则写路由必然生成ALL: 
导致报错
```invalid pattern: ALL:POST:/login URI should lead with '/'```

**Comment by mutiple** [comment]
看了源代码了解规则了，分组方式实现最后会groupALL(m.loginpath, m.login)
全局中间件bindhandler 注册。
有没有办法分组路由可以控制路由注册方法，毕竟真实投入生产的项目不会放开这么多的请求，对于项目来说有很大的安全隐患

**Comment by zcool321** [comment]
欢迎提交PR，这块我抽时间可以考虑下

**Comment by zcool321** [comment]
v1.4.5.1 已支持
