### ISSUE TITLE
是否可以自定义返回结果

### ISSUE THREAD

**Issue by ruinshe** [goflyfox/gtoken#3]
目前此框架返回的结果（至少默认的`login`和`logout`）用的是`gtoken`自己的一套返回结果和错误码，该返回结果是否可以自定义（甚至错误信息也想自定义;-)

**Comment by zcool321** [comment]
可以自己实现login和logout

       // 登录路径
	LoginPath string
	// 登录验证方法 return userKey 用户标识 如果userKey为空，结束执行
	LoginBeforeFunc func(r *ghttp.Request) (string, interface{})
	// 登录返回方法
	LoginAfterFunc func(r *ghttp.Request, respData Resp)
	// 登出地址
	LogoutPath string
	// 登出验证方法 return true 继续执行，否则结束执行
	LogoutBeforeFunc func(r *ghttp.Request) bool
	// 登出返回方法
	LogoutAfterFunc func(r *ghttp.Request, respData Resp)

	// 拦截地址
	AuthPaths g.SliceStr
	// 认证验证方法 return true 继续执行，否则结束执行
	AuthBeforeFunc func(r *ghttp.Request) bool
	// 认证返回方法
	AuthAfterFunc func(r *ghttp.Request, respData Resp)
