### ISSUE TITLE
第一次登录问题

### ISSUE THREAD

**Issue by MiltonErickson** [goflyfox/gtoken#32]
场景：
第一次登录，支持多端登录
问题：
当支持多端登录的时候，在放进token前，会进行一次缓存检查，getToken, (gtoken.go 78行）
然后进入getCache里，在这个方法里(gtoken_cache.go 50行),由于缓存里没有key，会log error一下：
g.Log().Error(ctx, "[GToken]cache get error", err)
这样，会导致打印堆栈信息，给日志收集带来不必要的歧义，建议使用Info或者Notice

**Comment by zcool321** [comment]
最好提供一下版本，正常访问应该没有这个错误吧

**Comment by zcool321** [comment]
如果是goftame2.0 可以更新下最新版本
