### ISSUE TITLE
gfile方法名替换问题

### ISSUE THREAD

**Issue by Arc-zlz** [goflyfox/gtoken#37]
![image](https://user-images.githubusercontent.com/26889461/156916708-c05cdef1-f968-4f25-996b-fa6ec41282cd.png)
在 github.com/gogf/gf/v2 v2.0.0-rc3 以上的版本  已经没有 gfile.TempDir 该方法 导致运行报错
![image](https://user-images.githubusercontent.com/26889461/156916755-72bde9ac-eb8d-4b00-98be-7d223fc06153.png)

**Comment by zcool321** [comment]
已更新，请升级到1.5.4
