### ISSUE TITLE
怎么适配gf init创建的项目

### ISSUE THREAD

**Issue by daydayup345** [goflyfox/gtoken#38]
标准的 gf init 项目
api.v1.user.go 
type UserLoginReq struct {
	g.Meta   `path:"/user/login" tags:"user" method:"post" summary:"You first hello api"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginRes struct {
	g.Meta `mime:"text/html" example:"string"`
}

controller.user.go 
func (c *cUser) Login(ctx context.Context, req *v1.UserLoginReq) (res *v1.UserLoginRes, err error) {
	fmt.Println(req.Username, req.Password)
	return
}

cmd.go
s.Group("/api", func(group *ghttp.RouterGroup) {
      group.Middleware(ghttp.MiddlewareHandlerResponse)
      group.Bind(
	      controller.User,
      )
      s.Run()
}

这种方式该怎么创建 gToken 实例呢？ 
LoginBeforeFunc:  该函数已经指定了参数类型的啊

**Comment by zcool321** [comment]
可以看下gtoken里面的examplae/sample
