### ISSUE TITLE
token是如何执行的

### ISSUE THREAD

**Issue by jinyuanqing** [goflyfox/gtoken#39]
![image](https://user-images.githubusercontent.com/12565969/163301731-e3e2b3bb-8957-4b81-9330-8988ae86dd52.png)

其中gtoken的LoginBeoreFunc对应的函数是在LoginPath路由前执行还是绑定执行呢.我从图片中可以看到执行LoginPath的路由,然后执行了绑定的LoginBeforeFunc函数.不知道这样对吗

**Comment by jinyuanqing** [comment]
用的是gf2

**Comment by Wyatex** [comment]
loginPath就是对应LoginBeforeFunc的
