### ISSUE TITLE
gf v1.11.5 error

### ISSUE THREAD

**Issue by tiger1103** [goflyfox/gtoken#4]
2020-03-04 21:54:45.561 build error:
# github.com/goflyfox/gtoken/gtoken
..\..\gopath\pkg\mod\github.com\goflyfox\gtoken@v1.3.11\gtoken\gtoken.go:397:41: not enough arguments in call to grand.Str
        have (number)
        want (string, int)

解决：
line 397 :
// 重新生成uuid
newUuid, err := gmd5.Encrypt(grand.Letters(10))

**Comment by zcool321** [comment]
升级最新版本即可
