### ISSUE TITLE
user auth uuid error错误

### ISSUE THREAD

**Issue by juhuatong** [goflyfox/gtoken#41]
`func (c *bToken) AuthAfterFunc(r *ghttp.Request, respData gtoken.Resp) {
	g.Log().Info(r.Context(), "这里是 gftoken 中间件*******")
	if respData.Success() {
		g.Log().Info(r.Context(), "每次都走到这里")
		//todo 往context里面注入用户信息
		r.Middleware.Next()
	} else {
		response.Error(true, r, "用户信息验证失败", "")
		r.ExitAll()
	}
}`

**Comment by juhuatong** [comment]
我自己的问题

**Comment by goodking-bq** [comment]
请问你怎么解决的  我不知道改哪里了也出现了这个问题
