### ISSUE TITLE
缓存超时时间刷新判断问题

### ISSUE THREAD

**Issue by kuaileshi1** [goflyfox/gtoken#9]
![image](https://user-images.githubusercontent.com/25023354/86070851-49007a80-bab0-11ea-9a26-55636962963f.png)

nowTime 取的gtime.Now().Millisecond()值，范围[0,999]。refreshTime取的gtime.Now().Millisecond() + m.MaxRefresh，该值正常情况会>999，这样if gconv.Int64(refreshTime) == 0 || nowTime > gconv.Int(refreshTime) { 判断刷新缓存的逻辑就永远执行不到。

**Comment by zcool321** [comment]
感谢反馈~这里时间函数使用有点问题

**Comment by zcool321** [comment]
v1.3.18 已修复
